name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge-snyk:
    runs-on: ubuntu-latest
    steps:
      - name: automerge Snyk
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{secrets.USER_GITHUB_TOKEN}}"
          MERGE_FORKS: false
          MERGE_DELETE_BRANCH: true
          MERGE_FILTER_AUTHOR: snyk-bot
          MERGE_LABELS: ''
  automerge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: automerge Dependabot
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{secrets.USER_GITHUB_TOKEN}}"
          MERGE_FORKS: false
          MERGE_DELETE_BRANCH: true
          MERGE_FILTER_AUTHOR: ''
          MERGE_LABELS: dependencies