name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
  pull_request_target:
  workflow_run:
    workflows: [Build, Test, Run tests]
    types: [completed]
    branches-ignore:
      - master
      - main
jobs:
  automerge-snyk:
    # https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-797125425
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    if: ${{github.event_name != 'pull_request_target'}}
    runs-on: ubuntu-latest
    steps:
      - name: automerge Snyk
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{secrets.USER_GITHUB_TOKEN}}"
          MERGE_FORKS: false
          MERGE_DELETE_BRANCH: true
          MERGE_FILTER_AUTHOR: snyk-bot
          MERGE_LABELS: ''
  automerge-dependabot:
    # https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-797125425
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    if: ${{(github.event_name == 'workflow_run' || github.event_name == 'pull_request_target') && github.actor == 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    steps:
      - name: automerge Dependabot
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{secrets.USER_GITHUB_TOKEN}}"
          MERGE_FORKS: false
          MERGE_DELETE_BRANCH: true
          MERGE_FILTER_AUTHOR: ''
          MERGE_LABELS: dependencies